### ISSUE TITLE
PowerShell Error

### ISSUE THREAD

**Issue by MarkusPriska** [scottmckendry/Windots#11]
I get the following error:
```
At C:\Users\MarkusPriska\Documents\WindowsPowerShell\profile.ps1:359 char:29
+     $gitUpdates = git fetch && git status
+                             ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidEndOfLine
```
When i launch PowerShell version 7.4.3

**Comment by scottmckendry** [comment]
Can you run `$PSVersionTable` after you get the error? Weird that PS7 is sourcing its profile from the `WindowsPowershell` folder.

I have a sneaking suspicion that this is PS5 😉

**Comment by MarkusPriska** [comment]
The problem i have is that powershell runs but looks a bit funny:
![image](https://github.com/user-attachments/assets/22681e86-4e24-4f8a-aa9b-8ddbec62fabb)

But then i run nvim from the WezTerm terminal:

![image](https://github.com/user-attachments/assets/2cfb22fd-f88b-48a2-8dfa-9777dc0ff234)

I keep getting weird error after weird error indicating something with the powershell

**Comment by scottmckendry** [comment]
I'm not sure what you mean by "looks weird"... if you mean the font, I agree. I tried a bunch of different fonts and font weights and found the JetBrains Mono looked best.

Undo the font changes you made [here](https://github.com/scottmckendry/Windots/commit/0bc3af8f1915ca96b0882b0166f1378cc794d025); I think it will look much better.

The supermaven error, I'm not so sure about... it's not a plugin I use so I'm probably not going to be a huge help here. I'm assuming `vim.opt.shell` is still set to `pwsh`?

Looking at the line where the error is coming from, it's trying to run `curl` - this will be using whatever shell is set in Neovim:
https://github.com/supermaven-inc/supermaven-nvim/blob/d71257f431e190d9236d7f30da4c2d659389e91f/lua/supermaven-nvim/binary/binary_fetcher.lua#L65

So it appears to me that for whatever reason, neovim is using `powershell` instead of `pwsh`.

If that's not the case, you can try deleting the `profile.ps1` from `Documents\WindowsPowershell` to see if that makes any difference.

**Comment by MarkusPriska** [comment]
Deleting the entire folder `Documents\WindowsPowershell` worked! Supermaven loaded correctly! Thanks!

Do you have any idea as to why this was caused?

As to why i wrote my terminal looked weird is beacuse when i run it on my home desktop the terminal has more text saying:
"~ with <symbol> v3.12.0"

**Comment by scottmckendry** [comment]
> Do you have any idea as to why this was caused?

My first guess would be that `setup.ps1` was run on PS5 at some point and created a symlinked profile that has compatibility problems.

I'll add a `#requires` statement at the top of this script so it doesn't happen in future installs.


> As to why i wrote my terminal looked weird is beacuse when i run it on my home desktop the terminal has more text saying: "~ with v3.12.0"

This is most likely Starship picking up on specific files in your home directory.

You can run `starship explain` to see what's causing it.

**Comment by MarkusPriska** [comment]
Thanks for the help!
Love using your config and setup!
